services:
  neo4j:
    container_name: shadowfleet-neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - $HOME/Documents/Projecten/shadowfleet_owners/data/neo4j/data:/data
      - $HOME/Documents/Projecten/shadowfleet_owners/data/neo4j/logs:/logs
      - $HOME/Documents/Projecten/shadowfleet_owners/data/processed:/var/lib/neo4j/import
      - $HOME/Documents/Projecten/shadowfleet_owners/data/neo4j/plugins:/plugins